import { defineComponent, rect, text, path, ellipse, node } from '@vmotion/sdk';
export default defineComponent({
  name: '表达式、布局与曲线路径',
  parameters: { speed: { type: 'number', default: 1, min: 0.1, max: 4 } },
  render(ctx, params) {
    const nodes = [
      text('heading', '属性联动 · 布局约束 · 曲线路径', {
        x: 44,
        y: 25,
        width: 1140,
        height: 64,
        fontSize: 36,
        fontWeight: 700,
        fill: '#e9f2ff',
      }),
      text('subtitle', '一个求值系统，共享画面、选框和 Agent 检查数据', {
        x: 46,
        y: 88,
        width: 1100,
        height: 35,
        fontSize: 18,
        fill: '#829cbb',
      }),
      rect('route-bg', { x: 44, y: 146, width: 820, height: 472, radius: 16, fill: '#15243a' }),
      text('route-title', '01 / SVG 曲线按弧长运动', {
        x: 70,
        y: 168,
        width: 760,
        height: 40,
        fontSize: 23,
        fontWeight: 700,
        fill: '#c5ddfa',
      }),
      path('route', 'M100 330 C210 180 380 520 490 330 C560 205 710 230 810 430', {
        stroke: '#507dba',
        strokeWidth: 3,
        fill: 'transparent',
      }),
      rect('marker', {
        width: 24,
        height: 14,
        originX: 12,
        originY: 7,
        radius: 3,
        fill: '#b4e2ff',
        motionPath: { nodeId: 'route', anchor: 'origin', autoRotate: true },
        expressions: { 'motionPath.progress': `frame / 119 * ${Number(params.speed)}` },
      }),
      ellipse('origin', { x: 94, y: 324, width: 12, height: 12, fill: '#698dba' }),
      text('follow', 'FOLLOW', {
        width: 140,
        height: 30,
        fontSize: 16,
        fontWeight: 700,
        fill: '#aed4ff',
        expressions: { x: 'clamp(layer("marker").x + 20, 70, 710)', y: 'layer("marker").y - 35' },
      }),
      text('route-note', '曲线位置 → 自动朝向 → 标签引用同一图层', {
        x: 72,
        y: 572,
        width: 730,
        height: 30,
        fontSize: 16,
        fill: '#829bbc',
      }),
      node({
        id: 'panel',
        type: 'group',
        width: 300,
        height: 320,
        x: 920,
        y: 204,
        expressions: { width: '280 + 35 * sin(time * Math.PI)' },
      }),
      rect('panel-bg', {
        parentId: 'panel',
        radius: 16,
        fill: '#24213c',
        layout: { reference: 'parent', insets: { left: 0, right: 0, top: 0, bottom: 0 } },
      }),
      text('panel-title', '02 / 响应式布局', {
        parentId: 'panel',
        width: 260,
        height: 40,
        fontSize: 22,
        fontWeight: 700,
        fill: '#d4c9f7',
        layout: {
          x: { at: 'start', self: 'start', offset: 20 },
          y: { at: 'start', self: 'start', offset: 20 },
        },
      }),
      rect('box-a', {
        parentId: 'panel',
        height: 60,
        radius: 8,
        fill: '#5a69a0',
        layout: {
          reference: 'parent',
          width: { value: 0.8 },
          x: { at: 'center', self: 'center' },
          y: { at: 'start', self: 'start', offset: 92 },
        },
      }),
      rect('box-b', {
        parentId: 'panel',
        height: 60,
        radius: 8,
        fill: '#706298',
        layout: {
          reference: 'parent',
          width: { value: 0.6 },
          x: { at: 'center', self: 'center' },
          y: { at: 'start', self: 'start', offset: 174 },
        },
      }),
      text('panel-note', '尺寸变化，锚点保持', {
        parentId: 'panel',
        width: 270,
        height: 32,
        fontSize: 16,
        fill: '#a89cc4',
        layout: {
          reference: 'parent',
          x: { at: 'center', self: 'center' },
          y: { at: 'end', self: 'end', offset: -18 },
        },
      }),
      text('links', '03 / 表达式依赖', {
        x: 910,
        y: 573,
        width: 320,
        height: 34,
        fontSize: 22,
        fontWeight: 700,
        fill: '#d0dfff',
      }),
      text('links-note', 'base / self / parent / layer(id)', {
        x: 910,
        y: 618,
        width: 320,
        height: 30,
        fontSize: 15,
        fill: '#839aba',
      }),
      text('footer', 'VMOTION / 随机帧求值 · 跨组件覆盖 · 原生预检', {
        x: 44,
        y: 682,
        width: 1150,
        height: 24,
        fontSize: 12,
        fill: '#6b84a5',
      }),
    ];
    return nodes;
  },
});
